### ISSUE TITLE
KeyError: 'x-picnic-auth'

### ISSUE THREAD

**Issue by Veldkornet** [MikeBrink/home-assistant-picnic#10]
Been getting this error for the past day or two:

```
2020-11-25 15:40:12 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up picnic platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/picnic/sensor.py", line 59, in async_setup_platform
    api = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/python_picnic_api/client.py", line 36, in __init__
    self.session.login(self._username, self._password, self._base_url)
  File "/usr/local/lib/python3.8/site-packages/python_picnic_api/session.py", line 33, in login
    self.headers.update({"x-picnic-auth": response.headers["x-picnic-auth"]})
  File "/usr/local/lib/python3.8/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-picnic-auth'
```

**Comment by don86nl** [comment]
Yes, me too. Sensors became unavailable.
Probably something changed on Picnic's side?

**Comment by MikeBrink** [comment]
Yes Picnic changed their API. I'll look into it tomorrow. It will probably require upgrading python_picnic_api through pip. I am not sure if I can do this from HACS.

**Comment by Veldkornet** [comment]
FYI it just started working again for me today...

**Comment by don86nl** [comment]
Yes, after restarting mine too!

**Comment by MikeBrink** [comment]
Weird, I wasn't able to reproduce the issue this weekend. Seems like Picnic was doing some work on their API and rolled it back just as I started working on it. 

I'll monitor the situation and when the problem reoccurs I'll try to catch the specific error.
